name: 'Compile Typst documents'
description: 'GitHub Action to compile Typst documents'
inputs:
  filenames:
    description: 'Define the filenames for the compiled typst documents'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download and extract Typst binary
      id: vars
      shell: bash
      run: |
        if [ "$RUNNER_OS" == 'Linux' ]; 
        then
             binary_type="unknown-linux-gnu"
             archive_extension=".tar.gz"
        elif [ "$RUNNER_OS" == 'Windows' ]; 
        then
             binary_type="pc-windows-msvc"
             archive_extension=".zip"
        else 
             binary_type="apple-darwin"
             archive_extension=".tar.gz"
        fi
        
        echo "binary_type=$binary_type" >> $GITHUB_OUTPUT
        
        echo Running on $RUNNER_OS extracting $binary_type$archive_extension
        curl -OL "https://github.com/typst/typst/releases/download/v0.1.0/typst-x86_64-${binary_type}${archive_extension}"

        if [ "$RUNNER_OS" == 'Windows' ]; 
        then
            7z x "typst-x86_64-${binary_type}${archive_extension}"
        else
            tar zxvf "typst-x86_64-${binary_type}${archive_extension}"
        fi
        
    - name: Compile Typst documents
      run: |
        paths="${{ inputs.filenames }}"
        paths=${paths//$'\n'/}
        echo Paths $paths
        
        for file in ${paths[@]}; do
          ./typst-x86_64-${{ steps.vars.outputs.binary_type }}/typst compile $file
        done
      shell: bash
